import { StyleSheet } from "react-native";
const Style = StyleSheet.create({
  container: {
    width: "100%",
    height: "100%",
    backgroundColor: "#e8c309",
  },
  flexContainer: {
    marginTop: 20,
    height: "90%",
    backgroundColor: "white",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  input: {
    marginTop: 166,
    width: 52,
    height: 50,
    margin: 15,
    marginTop: 10,
    fontSize: 20,
    borderRadius: 10,
    padding: 10,
    backgroundColor: "#e1f2f2",
  },
  button: {
    width: 160,
    height: 45,
    marginTop: 16,
    alignSelf: "center",
    alignItems: "center",
    backgroundColor: "#194792",
    borderRadius: 40,
    color: "white",
    shadowOffset: { width: -2, height: 4 },
    shadowColor: "#171717",
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  buttonSubmit: {
    width: 160,
    height: 45,
    marginTop: 166,
    alignSelf: "center",
    alignItems: "center",
    backgroundColor: "#194792",
    borderRadius: 40,
    color: "white",
    shadowOffset: { width: -2, height: 4 },
    shadowColor: "#171717",
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  Footerview: {
    marginTop: 22,
  },

  modalContainer: {
    width: "93%",
    height: "30%",
    backgroundColor: "white",
    padding: 25,
    borderRadius: 25,
    elevation: 20,
    alignSelf: "center",
    shadowOffset: { width: -2, height: 4 },
    shadowColor: "#171717",
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },

  viewModalBackground: {
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
});
export default Style;
