
export default Fonts = {
    fs58: { fontSize: 58, fontFamily: 'Roboto-Regular' },
    fs46: { fontSize: 46, fontFamily: 'Roboto-Regular' },
    fs36: { fontSize: 36, fontFamily: 'Roboto-Regular' },
    fs34: { fontSize: 34, fontFamily: 'Roboto-Regular' },
    fs26: { fontSize: 26, fontFamily: 'Roboto-Regular' },
    fs24: { fontSize: 24, fontFamily: 'Roboto-Regular' },
    fs22: { fontSize: 22, fontFamily: 'Roboto-Regular' },
    fs20: { fontSize: 20, fontFamily: 'Roboto-Regular' },
    fs18: { fontSize: 18, fontFamily: 'Roboto-Regular' },
    fs16: { fontSize: 16, fontFamily: 'Roboto-Regular' },
    fs15: { fontSize: 15, fontFamily: 'Roboto-Regular' },
    fs14: { fontSize: 14, fontFamily: 'Roboto-Regular' },
    fs12: { fontSize: 12, fontFamily: 'Roboto-Regular' },
    fs10: { fontSize: 10, fontFamily: 'Roboto-Regular' },

    fs58L: { fontSize: 58, fontFamily: 'Roboto-Light' },
    fs46L: { fontSize: 46, fontFamily: 'Roboto-Light' },
    fs26L: { fontSize: 26, fontFamily: 'Roboto-Light' },
    fs24L: { fontSize: 24, fontFamily: 'Roboto-Light' },
    fs22L: { fontSize: 22, fontFamily: 'Roboto-Light' },
    fs20L: { fontSize: 20, fontFamily: 'Roboto-Light' },
    fs18L: { fontSize: 18, fontFamily: 'Roboto-Light' },
    fs16L: { fontSize: 16, fontFamily: 'Roboto-Light' },
    fs15L: { fontSize: 15, fontFamily: 'Roboto-Light' },
    fs14L: { fontSize: 14, fontFamily: 'Roboto-Light' },
    fs12L: { fontSize: 12, fontFamily: 'Roboto-Light' },
    fs10L: { fontSize: 10, fontFamily: 'Roboto-Light' },

    fs58B: { fontSize: 58, fontFamily: 'Roboto-Bold' },
    fs46B: { fontSize: 46, fontFamily: 'Roboto-Bold' },
    fs36B: { fontSize: 36, fontFamily: 'Roboto-Bold' },
    fs30B: { fontSize: 30, fontFamily: 'Roboto-Bold' },
    fs26B: { fontSize: 26, fontFamily: 'Roboto-Bold' },
    fs24B: { fontSize: 24, fontFamily: 'Roboto-Bold' },
    fs22B: { fontSize: 22, fontFamily: 'Roboto-Bold' },
    fs20B: { fontSize: 20, fontFamily: 'Roboto-Bold' },
    fs18B: { fontSize: 18, fontFamily: 'Roboto-Bold' },
    fs16B: { fontSize: 16, fontFamily: 'Roboto-Bold' },
    fs15B: { fontSize: 15, fontFamily: 'Roboto-Bold' },
    fs14B: { fontSize: 14, fontFamily: 'Roboto-Bold' },
    fs12B: { fontSize: 12, fontFamily: 'Roboto-Bold' },
    fs10B: { fontSize: 10, fontFamily: 'Roboto-Bold' },

    fs58M: { fontSize: 58, fontFamily: 'Roboto-Medium' },
    fs46M: { fontSize: 46, fontFamily: 'Roboto-Medium' },
    fs36M: { fontSize: 36, fontFamily: 'Roboto-Medium' },
    fs34M: { fontSize: 34, fontFamily: 'Roboto-Medium' },
    fs26M: { fontSize: 26, fontFamily: 'Roboto-Medium' },
    fs24M: { fontSize: 24, fontFamily: 'Roboto-Medium' },
    fs22M: { fontSize: 22, fontFamily: 'Roboto-Medium' },
    fs20M: { fontSize: 20, fontFamily: 'Roboto-Medium' },
    fs18M: { fontSize: 18, fontFamily: 'Roboto-Medium' },
    fs16M: { fontSize: 16, fontFamily: 'Roboto-Medium' },
    fs15M: { fontSize: 15, fontFamily: 'Roboto-Medium' },
    fs14M: { fontSize: 14, fontFamily: 'Roboto-Medium' },
    fs12M: { fontSize: 12, fontFamily: 'Roboto-Medium' },
    fs10M: { fontSize: 10, fontFamily: 'Roboto-Medium' },
};
